### Ejercicio 1

Representar a un grafo utilizando una matriz de adyacencia. Sobre tal representación, se debe poder ejecutar los siguientes operadores:

- Minimales del grafo
- Maximales del grafo
- Vecindad derecha de un nodo
- Vecindad izquierda de un nodo

Los grafos se deben poder leer de los archivos provistos como ejemplo; hay dos formatos usados:

- csv mostrando la matriz (se deberán identificar a los nodos según la posición que tengan en la misma)
- json con la estructura del grafo

In [ ]:
import pandas as pd
import json

In [ ]:
m0 = pd.read_csv('/content/drive/MyDrive/Estructura de datis/Archivos_1/01.csv', header=None)

In [ ]:
# Leer matrices de adyacencia (CSV)
matrices = []
for i in range(1, 5):
    path = f'/content/drive/MyDrive/Estructura de datis/Archivos_1/0{i}.csv'
    df = pd.read_csv(path, header=None)
    matrices.append(df)

In [ ]:
matrices[0].head(6)

   0  1  2  3  4  5
0  1  0  0  0  0  0
1  0  1  0  0  0  0
2  0  0  1  0  0  0
3  0  0  0  1  0  0
4  0  0  0  0  1  0
5  0  0  0  0  0  1

In [ ]:
# Minimales: nodos que no reciben conexiones (columnas vacías) = FUENTES
def minimales(matriz):
    return [j for j in range(matriz.shape[1]) if matriz.iloc[:, j].sum() == 0]

# Maximales: nodos que no emiten conexiones (filas vacías) = SUMIDEROS
def maximales(matriz):
    return [i for i in range(matriz.shape[0]) if matriz.iloc[i, :].sum() == 0]

# Vecindad derecha: nodos a los que apunta un nodo
def vecindad_derecha(matriz, nodo):
    return [j for j in range(matriz.shape[1]) if matriz.iat[nodo, j] == 1]

# Vecindad izquierda: nodos que apuntan al nodo
def vecindad_izquierda(matriz, nodo):
    return [i for i in range(matriz.shape[0]) if matriz.iat[i, nodo] == 1]

In [ ]:
for idx, matriz in enumerate(matrices):
    print(f'\nMatriz {idx}:')
    print(f'  Maximales: {maximales(matriz)}')
    print(f'  Minimales: {minimales(matriz)}')

    for nodo in range(matriz.shape[0]):
        print(f'    Nodo {nodo} -> VD: {vecindad_derecha(matriz, nodo)} | VI: {vecindad_izquierda(matriz, nodo)}')

Matriz 0:
  Maximales: []
  Minimales: []
    Nodo 0 -> VD: [0] | VI: [0]
    Nodo 1 -> VD: [1] | VI: [1]
    Nodo 2 -> VD: [2] | VI: [2]
    Nodo 3 -> VD: [3] | VI: [3]
    Nodo 4 -> VD: [4] | VI: [4]
    Nodo 5 -> VD: [5] | VI: [5]

Matriz 1:
  Maximales: [0]
  Minimales: [4, 5]
    Nodo 0 -> VD: [] | VI: [4, 5]
    Nodo 1 -> VD: [1] | VI: [1]
    Nodo 2 -> VD: [2] | VI: [2]
    Nodo 3 -> VD: [3] | VI: [3]
    Nodo 4 -> VD: [0] | VI: []
    Nodo 5 -> VD: [0] | VI: []

Matriz 2:
  Maximales: [4]
  Minimales: [4]
    Nodo 0 -> VD: [5] | VI: [5]
    Nodo 1 -> VD: [1, 2] | VI: [1, 2]
    Nodo 2 -> VD: [1, 2] | VI: [1, 2]
    Nodo 3 -> VD: [3] | VI: [3]
    Nodo 4 -> VD: [] | VI: []
    Nodo 5 -> VD: [0] | VI: [0]

Matriz 3:
  Maximales: [4]
  Minimales: [4]
    Nodo 0 -> VD: [2, 5] | VI: [1, 5]
    Nodo 1 -> VD: [0, 1, 2] | VI: [1, 2]
    Nodo 2 -> VD: [1, 2] | VI: [0, 1, 2]
    Nodo 3 -> VD: [3] | VI: [3]
    Nodo 4 -> VD: [] | VI: []
    Nodo 5 -> VD: [0] | VI: [0]

In [ ]:
matrices[1]

   0  1  2  3  4  5
0  0  0  0  0  0  0
1  0  1  0  0  0  0
2  0  0  1  0  0  0
3  0  0  0  1  0  0
4  1  0  0  0  0  0
5  1  0  0  0  0  0

In [ ]:
#Abrir el JSON

with open('/content/drive/MyDrive/Estructura de datis/Archivos_1/01.json', 'r') as f:
    json_graph = json.load(f)

nodos_json = json_graph["P"]     # lista de nodos
adyacencia_json = json_graph["E"]  # diccionario: nodo -> lista de vecinos

In [ ]:
#Por alguna razon los nodos esta como strings. vamos a covnertirlos a enteros
nodos_json = list(map(int, nodos_json))
adyacencia_json = {int(k): list(map(int, v)) for k, v in adyacencia_json.items()}

In [ ]:
# Estas son las funciones mas faciles ya que literalmetne el json te las dice

def minimales_json(adyacencia, nodos):
    return [n for n in nodos if all(n not in vecinos for vecinos in adyacencia.values())]

def maximales_json(adyacencia):
    return [n for n, vecinos in adyacencia.items() if not vecinos]

def vecindad_derecha_json(adyacencia, nodo):
    return [n for n, vecinos in adyacencia.items() if nodo in vecinos]

def vecindad_izquierda_json(adyacencia, nodo):
    return [n for n, vecinos in adyacencia.items() if nodo in vecinos]

In [ ]:
print("Minimales (fuentes):", minimales_json(adyacencia_json, nodos_json))
print("Maximales (sumideros):", maximales_json(adyacencia_json))

for nodo in nodos_json:
    print(f"Nodo {nodo} → VD: {vecindad_derecha_json(adyacencia_json, nodo)} | VI: {vecindad_izquierda_json(adyacencia_json, nodo)}")

Minimales (fuentes): []
Maximales (sumideros): []
Nodo 1 → VD: [1] | VI: [1]
Nodo 2 → VD: [1, 2] | VI: [1, 2]
Nodo 3 → VD: [1, 3] | VI: [1, 3]
Nodo 4 → VD: [1, 2, 4] | VI: [1, 2, 4]
Nodo 5 → VD: [1, 5] | VI: [1, 5]
Nodo 6 → VD: [1, 2, 3, 6] | VI: [1, 2, 3, 6]
Nodo 7 → VD: [1, 7] | VI: [1, 7]
Nodo 8 → VD: [1, 2, 4, 8] | VI: [1, 2, 4, 8]
Nodo 9 → VD: [1, 3, 9] | VI: [1, 3, 9]
Nodo 10 → VD: [1, 2, 5, 10] | VI: [1, 2, 5, 10]
Nodo 11 → VD: [1, 11] | VI: [1, 11]
Nodo 12 → VD: [1, 2, 3, 4, 6, 12] | VI: [1, 2, 3, 4, 6, 12]
Nodo 13 → VD: [1, 13] | VI: [1, 13]
Nodo 14 → VD: [1, 2, 7, 14] | VI: [1, 2, 7, 14]
Nodo 15 → VD: [1, 3, 5, 15] | VI: [1, 3, 5, 15]
Nodo 16 → VD: [1, 2, 4, 8, 16] | VI: [1, 2, 4, 8, 16]
Nodo 17 → VD: [1, 17] | VI: [1, 17]
Nodo 18 → VD: [1, 2, 3, 6, 9, 18] | VI: [1, 2, 3, 6, 9, 18]
Nodo 19 → VD: [1, 19] | VI: [1, 19]
Nodo 20 → VD: [1, 2, 4, 5, 10, 20] | VI: [1, 2, 4, 5, 10, 20]
Nodo 21 → VD: [1, 3, 7, 21] | VI: [1, 3, 7, 21]
Nodo 22 → VD: [1, 2, 11, 22] | VI: [1, 2, 11, 22]
Nodo 23 → VD: [1, 23] | VI: [1, 23]
Nodo 24 → VD: [1, 2, 3, 4, 6, 8, 12, 24] | VI: [1, 2, 3, 4, 6, 8, 12, 24]
Nodo 25 → VD: [1, 5, 25] | VI: [1, 5, 25]
Nodo 26 → VD: [1, 2, 13, 26] | VI: [1, 2, 13, 26]
Nodo 27 → VD: [1, 3, 9, 27] | VI: [1, 3, 9, 27]
Nodo 28 → VD: [1, 2, 4, 7, 14, 28] | VI: [1, 2, 4, 7, 14, 28]
Nodo 29 → VD: [1, 29] | VI: [1, 29]
Nodo 30 → VD: [1, 2, 3, 5, 6, 10, 15, 30] | VI: [1, 2, 3, 5, 6, 10, 15, 30]
Nodo 31 → VD: [1, 31] | VI: [1, 31]
Nodo 32 → VD: [1, 2, 4, 8, 16, 32] | VI: [1, 2, 4, 8, 16, 32]
Nodo 33 → VD: [1, 3, 11, 33] | VI: [1, 3, 11, 33]
Nodo 34 → VD: [1, 2, 17, 34] | VI: [1, 2, 17, 34]
Nodo 35 → VD: [1, 5, 7, 35] | VI: [1, 5, 7, 35]
Nodo 36 → VD: [1, 2, 3, 4, 6, 9, 12, 18, 36] | VI: [1, 2, 3, 4, 6, 9, 12, 18, 36]
Nodo 37 → VD: [1, 37] | VI: [1, 37]
Nodo 38 → VD: [1, 2, 19, 38] | VI: [1, 2, 19, 38]
Nodo 39 → VD: [1, 3, 13, 39] | VI: [1, 3, 13, 39]
Nodo 40 → VD: [1, 2, 4, 5, 8, 10, 20, 40] | VI: [1, 2, 4, 5, 8, 10, 20, 40]
Nodo 41 → VD: [1, 41] | VI: [1, 41]
Nodo 42 → VD: [1, 2, 3, 6, 7, 14, 21, 42] | VI: [1, 2, 3, 6, 7, 14, 21, 42]
Nodo 43 → VD: [1, 43] | VI: [1, 43]
Nodo 44 → VD: [1, 2, 4, 11, 22, 44] | VI: [1, 2, 4, 11, 22, 44]
Nodo 45 → VD: [1, 3, 5, 9, 15, 45] | VI: [1, 3, 5, 9, 15, 45]
Nodo 46 → VD: [1, 2, 23, 46] | VI: [1, 2, 23, 46]
Nodo 47 → VD: [1, 47] | VI: [1, 47]
Nodo 48 → VD: [1, 2, 3, 4, 6, 8, 12, 16, 24, 48] | VI: [1, 2, 3, 4, 6, 8, 12, 16, 24, 48]
Nodo 49 → VD: [1, 7, 49] | VI: [1, 7, 49]
Nodo 50 → VD: [1, 2, 5, 10, 25, 50] | VI: [1, 2, 5, 10, 25, 50]
Nodo 51 → VD: [1, 3, 17, 51] | VI: [1, 3, 17, 51]
Nodo 52 → VD: [1, 2, 4, 13, 26, 52] | VI: [1, 2, 4, 13, 26, 52]
Nodo 53 → VD: [1, 53] | VI: [1, 53]
Nodo 54 → VD: [1, 2, 3, 6, 9, 18, 27, 54] | VI: [1, 2, 3, 6, 9, 18, 27, 54]
Nodo 55 → VD: [1, 5, 11, 55] | VI: [1, 5, 11, 55]
Nodo 56 → VD: [1, 2, 4, 7, 8, 14, 28, 56] | VI: [1, 2, 4, 7, 8, 14, 28, 56]
Nodo 57 → VD: [1, 3, 19, 57] | VI: [1, 3, 19, 57]
Nodo 58 → VD: [1, 2, 29, 58] | VI: [1, 2, 29, 58]
Nodo 59 → VD: [1, 59] | VI: [1, 59]
Nodo 60 → VD: [1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60] | VI: [1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60]
Nodo 61 → VD: [1, 61] | VI: [1, 61]
Nodo 62 → VD: [1, 2, 31, 62] | VI: [1, 2, 31, 62]
Nodo 63 → VD: [1, 3, 7, 9, 21, 63] | VI: [1, 3, 7, 9, 21, 63]
Nodo 64 → VD: [1, 2, 4, 8, 16, 32, 64] | VI: [1, 2, 4, 8, 16, 32, 64]
Nodo 65 → VD: [1, 5, 13, 65] | VI: [1, 5, 13, 65]
Nodo 66 → VD: [1, 2, 3, 6, 11, 22, 33, 66] | VI: [1, 2, 3, 6, 11, 22, 33, 66]
Nodo 67 → VD: [1, 67] | VI: [1, 67]
Nodo 68 → VD: [1, 2, 4, 17, 34, 68] | VI: [1, 2, 4, 17, 34, 68]
Nodo 69 → VD: [1, 3, 23, 69] | VI: [1, 3, 23, 69]
Nodo 70 → VD: [1, 2, 5, 7, 10, 14, 35, 70] | VI: [1, 2, 5, 7, 10, 14, 35, 70]
Nodo 71 → VD: [1, 71] | VI: [1, 71]
Nodo 72 → VD: [1, 2, 3, 4, 6, 8, 9, 12, 18, 24, 36, 72] | VI: [1, 2, 3, 4, 6, 8, 9, 12, 18, 24, 36, 72]
Nodo 73 → VD: [1, 73] | VI: [1, 73]
Nodo 74 → VD: [1, 2, 37, 74] | VI: [1, 2, 37, 74]
Nodo 75 → VD: [1, 3, 5, 15, 25, 75] | VI: [1, 3, 5, 15, 25, 75]
Nodo 76 → VD: [1, 2, 4, 19, 38, 76] | VI: [1, 2, 4, 19, 38, 76]
Nodo 77 → VD: [1, 7, 11, 77] | VI: [1, 7, 11, 77]
Nodo 78 → VD: [1, 2, 3, 6, 13, 26, 39, 78] | VI: [1, 2, 3, 6, 13, 26, 39, 78]
Nodo 79 → VD: [1, 79] | VI: [1, 79]
Nodo 80 → VD: [1, 2, 4, 5, 8, 10, 16, 20, 40, 80] | VI: [1, 2, 4, 5, 8, 10, 16, 20, 40, 80]
Nodo 81 → VD: [1, 3, 9, 27, 81] | VI: [1, 3, 9, 27, 81]
Nodo 82 → VD: [1, 2, 41, 82] | VI: [1, 2, 41, 82]
Nodo 83 → VD: [1, 83] | VI: [1, 83]
Nodo 84 → VD: [1, 2, 3, 4, 6, 7, 12, 14, 21, 28, 42, 84] | VI: [1, 2, 3, 4, 6, 7, 12, 14, 21, 28, 42, 84]
Nodo 85 → VD: [1, 5, 17, 85] | VI: [1, 5, 17, 85]
Nodo 86 → VD: [1, 2, 43, 86] | VI: [1, 2, 43, 86]
Nodo 87 → VD: [1, 3, 29, 87] | VI: [1, 3, 29, 87]
Nodo 88 → VD: [1, 2, 4, 8, 11, 22, 44, 88] | VI: [1, 2, 4, 8, 11, 22, 44, 88]
Nodo 89 → VD: [1, 89] | VI: [1, 89]
Nodo 90 → VD: [1, 2, 3, 5, 6, 9, 10, 15, 18, 30, 45, 90] | VI: [1, 2, 3, 5, 6, 9, 10, 15, 18, 30, 45, 90]
Nodo 91 → VD: [1, 7, 13, 91] | VI: [1, 7, 13, 91]
Nodo 92 → VD: [1, 2, 4, 23, 46, 92] | VI: [1, 2, 4, 23, 46, 92]
Nodo 93 → VD: [1, 3, 31, 93] | VI: [1, 3, 31, 93]
Nodo 94 → VD: [1, 2, 47, 94] | VI: [1, 2, 47, 94]
Nodo 95 → VD: [1, 5, 19, 95] | VI: [1, 5, 19, 95]
Nodo 96 → VD: [1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 96] | VI: [1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 96]
Nodo 97 → VD: [1, 97] | VI: [1, 97]
Nodo 98 → VD: [1, 2, 7, 14, 49, 98] | VI: [1, 2, 7, 14, 49, 98]
Nodo 99 → VD: [1, 3, 9, 11, 33, 99] | VI: [1, 3, 9, 11, 33, 99]
Nodo 100 → VD: [1, 2, 4, 5, 10, 20, 25, 50, 100] | VI: [1, 2, 4, 5, 10, 20, 25, 50, 100]
Nodo 101 → VD: [1, 101] | VI: [1, 101]
Nodo 102 → VD: [1, 2, 3, 6, 17, 34, 51, 102] | VI: [1, 2, 3, 6, 17, 34, 51, 102]
Nodo 103 → VD: [1, 103] | VI: [1, 103]
Nodo 104 → VD: [1, 2, 4, 8, 13, 26, 52, 104] | VI: [1, 2, 4, 8, 13, 26, 52, 104]
Nodo 105 → VD: [1, 3, 5, 7, 15, 21, 35, 105] | VI: [1, 3, 5, 7, 15, 21, 35, 105]
Nodo 106 → VD: [1, 2, 53, 106] | VI: [1, 2, 53, 106]
Nodo 107 → VD: [1, 107] | VI: [1, 107]
Nodo 108 → VD: [1, 2, 3, 4, 6, 9, 12, 18, 27, 36, 54, 108] | VI: [1, 2, 3, 4, 6, 9, 12, 18, 27, 36, 54, 108]
Nodo 109 → VD: [1, 109] | VI: [1, 109]
Nodo 110 → VD: [1, 2, 5, 10, 11, 22, 55, 110] | VI: [1, 2, 5, 10, 11, 22, 55, 110]
Nodo 111 → VD: [1, 3, 37, 111] | VI: [1, 3, 37, 111]
Nodo 112 → VD: [1, 2, 4, 7, 8, 14, 16, 28, 56, 112] | VI: [1, 2, 4, 7, 8, 14, 16, 28, 56, 112]
Nodo 113 → VD: [1, 113] | VI: [1, 113]
Nodo 114 → VD: [1, 2, 3, 6, 19, 38, 57, 114] | VI: [1, 2, 3, 6, 19, 38, 57, 114]
Nodo 115 → VD: [1, 5, 23, 115] | VI: [1, 5, 23, 115]
Nodo 116 → VD: [1, 2, 4, 29, 58, 116] | VI: [1, 2, 4, 29, 58, 116]
Nodo 117 → VD: [1, 3, 9, 13, 39, 117] | VI: [1, 3, 9, 13, 39, 117]
Nodo 118 → VD: [1, 2, 59, 118] | VI: [1, 2, 59, 118]
Nodo 119 → VD: [1, 7, 17, 119] | VI: [1, 7, 17, 119]
Nodo 120 → VD: [1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 20, 24, 30, 40, 60, 120] | VI: [1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 20, 24, 30, 40, 60, 120]
Nodo 121 → VD: [1, 11, 121] | VI: [1, 11, 121]
Nodo 122 → VD: [1, 2, 61, 122] | VI: [1, 2, 61, 122]
Nodo 123 → VD: [1, 3, 41, 123] | VI: [1, 3, 41, 123]
Nodo 124 → VD: [1, 2, 4, 31, 62, 124] | VI: [1, 2, 4, 31, 62, 124]
Nodo 125 → VD: [1, 5, 25, 125] | VI: [1, 5, 25, 125]
Nodo 126 → VD: [1, 2, 3, 6, 7, 9, 14, 18, 21, 42, 63, 126] | VI: [1, 2, 3, 6, 7, 9, 14, 18, 21, 42, 63, 126]
Nodo 127 → VD: [1, 127] | VI: [1, 127]
Nodo 128 → VD: [1, 2, 4, 8, 16, 32, 64, 128] | VI: [1, 2, 4, 8, 16, 32, 64, 128]
Nodo 129 → VD: [1, 3, 43, 129] | VI: [1, 3, 43, 129]
Nodo 130 → VD: [1, 2, 5, 10, 13, 26, 65, 130] | VI: [1, 2, 5, 10, 13, 26, 65, 130]
Nodo 131 → VD: [1, 131] | VI: [1, 131]
Nodo 132 → VD: [1, 2, 3, 4, 6, 11, 12, 22, 33, 44, 66, 132] | VI: [1, 2, 3, 4, 6, 11, 12, 22, 33, 44, 66, 132]
Nodo 133 → VD: [1, 7, 19, 133] | VI: [1, 7, 19, 133]
Nodo 134 → VD: [1, 2, 67, 134] | VI: [1, 2, 67, 134]
Nodo 135 → VD: [1, 3, 5, 9, 15, 27, 45, 135] | VI: [1, 3, 5, 9, 15, 27, 45, 135]
Nodo 136 → VD: [1, 2, 4, 8, 17, 34, 68, 136] | VI: [1, 2, 4, 8, 17, 34, 68, 136]
Nodo 137 → VD: [1, 137] | VI: [1, 137]
Nodo 138 → VD: [1, 2, 3, 6, 23, 46, 69, 138] | VI: [1, 2, 3, 6, 23, 46, 69, 138]
Nodo 139 → VD: [1, 139] | VI: [1, 139]
Nodo 140 → VD: [1, 2, 4, 5, 7, 10, 14, 20, 28, 35, 70, 140] | VI: [1, 2, 4, 5, 7, 10, 14, 20, 28, 35, 70, 140]
Nodo 141 → VD: [1, 3, 47, 141] | VI: [1, 3, 47, 141]
Nodo 142 → VD: [1, 2, 71, 142] | VI: [1, 2, 71, 142]
Nodo 143 → VD: [1, 11, 13, 143] | VI: [1, 11, 13, 143]
Nodo 144 → VD: [1, 2, 3, 4, 6, 8, 9, 12, 16, 18, 24, 36, 48, 72, 144] | VI: [1, 2, 3, 4, 6, 8, 9, 12, 16, 18, 24, 36, 48, 72, 144]
Nodo 145 → VD: [1, 5, 29, 145] | VI: [1, 5, 29, 145]
Nodo 146 → VD: [1, 2, 73, 146] | VI: [1, 2, 73, 146]
Nodo 147 → VD: [1, 3, 7, 21, 49, 147] | VI: [1, 3, 7, 21, 49, 147]
Nodo 148 → VD: [1, 2, 4, 37, 74, 148] | VI: [1, 2, 4, 37, 74, 148]
Nodo 149 → VD: [1, 149] | VI: [1, 149]
Nodo 150 → VD: [1, 2, 3, 5, 6, 10, 15, 25, 30, 50, 75, 150] | VI: [1, 2, 3, 5, 6, 10, 15, 25, 30, 50, 75, 150]
Nodo 151 → VD: [1, 151] | VI: [1, 151]
Nodo 152 → VD: [1, 2, 4, 8, 19, 38, 76, 152] | VI: [1, 2, 4, 8, 19, 38, 76, 152]
Nodo 153 → VD: [1, 3, 9, 17, 51, 153] | VI: [1, 3, 9, 17, 51, 153]
Nodo 154 → VD: [1, 2, 7, 11, 14, 22, 77, 154] | VI: [1, 2, 7, 11, 14, 22, 77, 154]
Nodo 155 → VD: [1, 5, 31, 155] | VI: [1, 5, 31, 155]
Nodo 156 → VD: [1, 2, 3, 4, 6, 12, 13, 26, 39, 52, 78, 156] | VI: [1, 2, 3, 4, 6, 12, 13, 26, 39, 52, 78, 156]
Nodo 157 → VD: [1, 157] | VI: [1, 157]
Nodo 158 → VD: [1, 2, 79, 158] | VI: [1, 2, 79, 158]
Nodo 159 → VD: [1, 3, 53, 159] | VI: [1, 3, 53, 159]
Nodo 160 → VD: [1, 2, 4, 5, 8, 10, 16, 20, 32, 40, 80, 160] | VI: [1, 2, 4, 5, 8, 10, 16, 20, 32, 40, 80, 160]
Nodo 161 → VD: [1, 7, 23, 161] | VI: [1, 7, 23, 161]
Nodo 162 → VD: [1, 2, 3, 6, 9, 18, 27, 54, 81, 162] | VI: [1, 2, 3, 6, 9, 18, 27, 54, 81, 162]
Nodo 163 → VD: [1, 163] | VI: [1, 163]
Nodo 164 → VD: [1, 2, 4, 41, 82, 164] | VI: [1, 2, 4, 41, 82, 164]
Nodo 165 → VD: [1, 3, 5, 11, 15, 33, 55, 165] | VI: [1, 3, 5, 11, 15, 33, 55, 165]
Nodo 166 → VD: [1, 2, 83, 166] | VI: [1, 2, 83, 166]
Nodo 167 → VD: [1, 167] | VI: [1, 167]
Nodo 168 → VD: [1, 2, 3, 4, 6, 7, 8, 12, 14, 21, 24, 28, 42, 56, 84, 168] | VI: [1, 2, 3, 4, 6, 7, 8, 12, 14, 21, 24, 28, 42, 56, 84, 168]
Nodo 169 → VD: [1, 13, 169] | VI: [1, 13, 169]
Nodo 170 → VD: [1, 2, 5, 10, 17, 34, 85, 170] | VI: [1, 2, 5, 10, 17, 34, 85, 170]
Nodo 171 → VD: [1, 3, 9, 19, 57, 171] | VI: [1, 3, 9, 19, 57, 171]
Nodo 172 → VD: [1, 2, 4, 43, 86, 172] | VI: [1, 2, 4, 43, 86, 172]
Nodo 173 → VD: [1, 173] | VI: [1, 173]
Nodo 174 → VD: [1, 2, 3, 6, 29, 58, 87, 174] | VI: [1, 2, 3, 6, 29, 58, 87, 174]
Nodo 175 → VD: [1, 5, 7, 25, 35, 175] | VI: [1, 5, 7, 25, 35, 175]
Nodo 176 → VD: [1, 2, 4, 8, 11, 16, 22, 44, 88, 176] | VI: [1, 2, 4, 8, 11, 16, 22, 44, 88, 176]
Nodo 177 → VD: [1, 3, 59, 177] | VI: [1, 3, 59, 177]
Nodo 178 → VD: [1, 2, 89, 178] | VI: [1, 2, 89, 178]
Nodo 179 → VD: [1, 179] | VI: [1, 179]
Nodo 180 → VD: [1, 2, 3, 4, 5, 6, 9, 10, 12, 15, 18, 20, 30, 36, 45, 60, 90, 180] | VI: [1, 2, 3, 4, 5, 6, 9, 10, 12, 15, 18, 20, 30, 36, 45, 60, 90, 180]
Nodo 181 → VD: [1, 181] | VI: [1, 181]
Nodo 182 → VD: [1, 2, 7, 13, 14, 26, 91, 182] | VI: [1, 2, 7, 13, 14, 26, 91, 182]
Nodo 183 → VD: [1, 3, 61, 183] | VI: [1, 3, 61, 183]
Nodo 184 → VD: [1, 2, 4, 8, 23, 46, 92, 184] | VI: [1, 2, 4, 8, 23, 46, 92, 184]
Nodo 185 → VD: [1, 5, 37, 185] | VI: [1, 5, 37, 185]
Nodo 186 → VD: [1, 2, 3, 6, 31, 62, 93, 186] | VI: [1, 2, 3, 6, 31, 62, 93, 186]
Nodo 187 → VD: [1, 11, 17, 187] | VI: [1, 11, 17, 187]
Nodo 188 → VD: [1, 2, 4, 47, 94, 188] | VI: [1, 2, 4, 47, 94, 188]
Nodo 189 → VD: [1, 3, 7, 9, 21, 27, 63, 189] | VI: [1, 3, 7, 9, 21, 27, 63, 189]
Nodo 190 → VD: [1, 2, 5, 10, 19, 38, 95, 190] | VI: [1, 2, 5, 10, 19, 38, 95, 190]
Nodo 191 → VD: [1, 191] | VI: [1, 191]
Nodo 192 → VD: [1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64, 96, 192] | VI: [1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64, 96, 192]
Nodo 193 → VD: [1, 193] | VI: [1, 193]
Nodo 194 → VD: [1, 2, 97, 194] | VI: [1, 2, 97, 194]
Nodo 195 → VD: [1, 3, 5, 13, 15, 39, 65, 195] | VI: [1, 3, 5, 13, 15, 39, 65, 195]
Nodo 196 → VD: [1, 2, 4, 7, 14, 28, 49, 98, 196] | VI: [1, 2, 4, 7, 14, 28, 49, 98, 196]
Nodo 197 → VD: [1, 197] | VI: [1, 197]
Nodo 198 → VD: [1, 2, 3, 6, 9, 11, 18, 22, 33, 66, 99, 198] | VI: [1, 2, 3, 6, 9, 11, 18, 22, 33, 66, 99, 198]
Nodo 199 → VD: [1, 199] | VI: [1, 199]
Nodo 200 → VD: [1, 2, 4, 5, 8, 10, 20, 25, 40, 50, 100, 200] | VI: [1, 2, 4, 5, 8, 10, 20, 25, 40, 50, 100, 200]
Nodo 201 → VD: [1, 3, 67, 201] | VI: [1, 3, 67, 201]
Nodo 202 → VD: [1, 2, 101, 202] | VI: [1, 2, 101, 202]
Nodo 203 → VD: [1, 7, 29, 203] | VI: [1, 7, 29, 203]
Nodo 204 → VD: [1, 2, 3, 4, 6, 12, 17, 34, 51, 68, 102, 204] | VI: [1, 2, 3, 4, 6, 12, 17, 34, 51, 68, 102, 204]
Nodo 205 → VD: [1, 5, 41, 205] | VI: [1, 5, 41, 205]
Nodo 206 → VD: [1, 2, 103, 206] | VI: [1, 2, 103, 206]
Nodo 207 → VD: [1, 3, 9, 23, 69, 207] | VI: [1, 3, 9, 23, 69, 207]
Nodo 208 → VD: [1, 2, 4, 8, 13, 16, 26, 52, 104, 208] | VI: [1, 2, 4, 8, 13, 16, 26, 52, 104, 208]
Nodo 209 → VD: [1, 11, 19, 209] | VI: [1, 11, 19, 209]
Nodo 210 → VD: [1, 2, 3, 5, 6, 7, 10, 14, 15, 21, 30, 35, 42, 70, 105, 210] | VI: [1, 2, 3, 5, 6, 7, 10, 14, 15, 21, 30, 35, 42, 70, 105, 210]
Nodo 211 → VD: [1, 211] | VI: [1, 211]
Nodo 212 → VD: [1, 2, 4, 53, 106, 212] | VI: [1, 2, 4, 53, 106, 212]
Nodo 213 → VD: [1, 3, 71, 213] | VI: [1, 3, 71, 213]
Nodo 214 → VD: [1, 2, 107, 214] | VI: [1, 2, 107, 214]
Nodo 215 → VD: [1, 5, 43, 215] | VI: [1, 5, 43, 215]
Nodo 216 → VD: [1, 2, 3, 4, 6, 8, 9, 12, 18, 24, 27, 36, 54, 72, 108, 216] | VI: [1, 2, 3, 4, 6, 8, 9, 12, 18, 24, 27, 36, 54, 72, 108, 216]
Nodo 217 → VD: [1, 7, 31, 217] | VI: [1, 7, 31, 217]
Nodo 218 → VD: [1, 2, 109, 218] | VI: [1, 2, 109, 218]
Nodo 219 → VD: [1, 3, 73, 219] | VI: [1, 3, 73, 219]
Nodo 220 → VD: [1, 2, 4, 5, 10, 11, 20, 22, 44, 55, 110, 220] | VI: [1, 2, 4, 5, 10, 11, 20, 22, 44, 55, 110, 220]
Nodo 221 → VD: [1, 13, 17, 221] | VI: [1, 13, 17, 221]
Nodo 222 → VD: [1, 2, 3, 6, 37, 74, 111, 222] | VI: [1, 2, 3, 6, 37, 74, 111, 222]
Nodo 223 → VD: [1, 223] | VI: [1, 223]
Nodo 224 → VD: [1, 2, 4, 7, 8, 14, 16, 28, 32, 56, 112, 224] | VI: [1, 2, 4, 7, 8, 14, 16, 28, 32, 56, 112, 224]
Nodo 225 → VD: [1, 3, 5, 9, 15, 25, 45, 75, 225] | VI: [1, 3, 5, 9, 15, 25, 45, 75, 225]
Nodo 226 → VD: [1, 2, 113, 226] | VI: [1, 2, 113, 226]
Nodo 227 → VD: [1, 227] | VI: [1, 227]
Nodo 228 → VD: [1, 2, 3, 4, 6, 12, 19, 38, 57, 76, 114, 228] | VI: [1, 2, 3, 4, 6, 12, 19, 38, 57, 76, 114, 228]
Nodo 229 → VD: [1, 229] | VI: [1, 229]
Nodo 230 → VD: [1, 2, 5, 10, 23, 46, 115, 230] | VI: [1, 2, 5, 10, 23, 46, 115, 230]
Nodo 231 → VD: [1, 3, 7, 11, 21, 33, 77, 231] | VI: [1, 3, 7, 11, 21, 33, 77, 231]
Nodo 232 → VD: [1, 2, 4, 8, 29, 58, 116, 232] | VI: [1, 2, 4, 8, 29, 58, 116, 232]
Nodo 233 → VD: [1, 233] | VI: [1, 233]
Nodo 234 → VD: [1, 2, 3, 6, 9, 13, 18, 26, 39, 78, 117, 234] | VI: [1, 2, 3, 6, 9, 13, 18, 26, 39, 78, 117, 234]
Nodo 235 → VD: [1, 5, 47, 235] | VI: [1, 5, 47, 235]
Nodo 236 → VD: [1, 2, 4, 59, 118, 236] | VI: [1, 2, 4, 59, 118, 236]
Nodo 237 → VD: [1, 3, 79, 237] | VI: [1, 3, 79, 237]
Nodo 238 → VD: [1, 2, 7, 14, 17, 34, 119, 238] | VI: [1, 2, 7, 14, 17, 34, 119, 238]
Nodo 239 → VD: [1, 239] | VI: [1, 239]
Nodo 240 → VD: [1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 16, 20, 24, 30, 40, 48, 60, 80, 120, 240] | VI: [1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 16, 20, 24, 30, 40, 48, 60, 80, 120, 240]
Nodo 241 → VD: [1, 241] | VI: [1, 241]
Nodo 242 → VD: [1, 2, 11, 22, 121, 242] | VI: [1, 2, 11, 22, 121, 242]
Nodo 243 → VD: [1, 3, 9, 27, 81, 243] | VI: [1, 3, 9, 27, 81, 243]
Nodo 244 → VD: [1, 2, 4, 61, 122, 244] | VI: [1, 2, 4, 61, 122, 244]
Nodo 245 → VD: [1, 5, 7, 35, 49, 245] | VI: [1, 5, 7, 35, 49, 245]
Nodo 246 → VD: [1, 2, 3, 6, 41, 82, 123, 246] | VI: [1, 2, 3, 6, 41, 82, 123, 246]
Nodo 247 → VD: [1, 13, 19, 247] | VI: [1, 13, 19, 247]
Nodo 248 → VD: [1, 2, 4, 8, 31, 62, 124, 248] | VI: [1, 2, 4, 8, 31, 62, 124, 248]
Nodo 249 → VD: [1, 3, 83, 249] | VI: [1, 3, 83, 249]
Nodo 250 → VD: [1, 2, 5, 10, 25, 50, 125, 250] | VI: [1, 2, 5, 10, 25, 50, 125, 250]
Nodo 251 → VD: [1, 251] | VI: [1, 251]
Nodo 252 → VD: [1, 2, 3, 4, 6, 7, 9, 12, 14, 18, 21, 28, 36, 42, 63, 84, 126, 252] | VI: [1, 2, 3, 4, 6, 7, 9, 12, 14, 18, 21, 28, 36, 42, 63, 84, 126, 252]
Nodo 253 → VD: [1, 11, 23, 253] | VI: [1, 11, 23, 253]
Nodo 254 → VD: [1, 2, 127, 254] | VI: [1, 2, 127, 254]
Nodo 255 → VD: [1, 3, 5, 15, 17, 51, 85, 255] | VI: [1, 3, 5, 15, 17, 51, 85, 255]
Nodo 256 → VD: [1, 2, 4, 8, 16, 32, 64, 128, 256] | VI: [1, 2, 4, 8, 16, 32, 64, 128, 256]
Nodo 257 → VD: [1, 257] | VI: [1, 257]
Nodo 258 → VD: [1, 2, 3, 6, 43, 86, 129, 258] | VI: [1, 2, 3, 6, 43, 86, 129, 258]
Nodo 259 → VD: [1, 7, 37, 259] | VI: [1, 7, 37, 259]
Nodo 260 → VD: [1, 2, 4, 5, 10, 13, 20, 26, 52, 65, 130, 260] | VI: [1, 2, 4, 5, 10, 13, 20, 26, 52, 65, 130, 260]
Nodo 261 → VD: [1, 3, 9, 29, 87, 261] | VI: [1, 3, 9, 29, 87, 261]
Nodo 262 → VD: [1, 2, 131, 262] | VI: [1, 2, 131, 262]
Nodo 263 → VD: [1, 263] | VI: [1, 263]
Nodo 264 → VD: [1, 2, 3, 4, 6, 8, 11, 12, 22, 24, 33, 44, 66, 88, 132, 264] | VI: [1, 2, 3, 4, 6, 8, 11, 12, 22, 24, 33, 44, 66, 88, 132, 264]
Nodo 265 → VD: [1, 5, 53, 265] | VI: [1, 5, 53, 265]
Nodo 266 → VD: [1, 2, 7, 14, 19, 38, 133, 266] | VI: [1, 2, 7, 14, 19, 38, 133, 266]
Nodo 267 → VD: [1, 3, 89, 267] | VI: [1, 3, 89, 267]
Nodo 268 → VD: [1, 2, 4, 67, 134, 268] | VI: [1, 2, 4, 67, 134, 268]
Nodo 269 → VD: [1, 269] | VI: [1, 269]
Nodo 270 → VD: [1, 2, 3, 5, 6, 9, 10, 15, 18, 27, 30, 45, 54, 90, 135, 270] | VI: [1, 2, 3, 5, 6, 9, 10, 15, 18, 27, 30, 45, 54, 90, 135, 270]
Nodo 271 → VD: [1, 271] | VI: [1, 271]
Nodo 272 → VD: [1, 2, 4, 8, 16, 17, 34, 68, 136, 272] | VI: [1, 2, 4, 8, 16, 17, 34, 68, 136, 272]
Nodo 273 → VD: [1, 3, 7, 13, 21, 39, 91, 273] | VI: [1, 3, 7, 13, 21, 39, 91, 273]
Nodo 274 → VD: [1, 2, 137, 274] | VI: [1, 2, 137, 274]
Nodo 275 → VD: [1, 5, 11, 25, 55, 275] | VI: [1, 5, 11, 25, 55, 275]
Nodo 276 → VD: [1, 2, 3, 4, 6, 12, 23, 46, 69, 92, 138, 276] | VI: [1, 2, 3, 4, 6, 12, 23, 46, 69, 92, 138, 276]
Nodo 277 → VD: [1, 277] | VI: [1, 277]
Nodo 278 → VD: [1, 2, 139, 278] | VI: [1, 2, 139, 278]
Nodo 279 → VD: [1, 3, 9, 31, 93, 279] | VI: [1, 3, 9, 31, 93, 279]
Nodo 280 → VD: [1, 2, 4, 5, 7, 8, 10, 14, 20, 28, 35, 40, 56, 70, 140, 280] | VI: [1, 2, 4, 5, 7, 8, 10, 14, 20, 28, 35, 40, 56, 70, 140, 280]
Nodo 281 → VD: [1, 281] | VI: [1, 281]
Nodo 282 → VD: [1, 2, 3, 6, 47, 94, 141, 282] | VI: [1, 2, 3, 6, 47, 94, 141, 282]
Nodo 283 → VD: [1, 283] | VI: [1, 283]
Nodo 284 → VD: [1, 2, 4, 71, 142, 284] | VI: [1, 2, 4, 71, 142, 284]
Nodo 285 → VD: [1, 3, 5, 15, 19, 57, 95, 285] | VI: [1, 3, 5, 15, 19, 57, 95, 285]
Nodo 286 → VD: [1, 2, 11, 13, 22, 26, 143, 286] | VI: [1, 2, 11, 13, 22, 26, 143, 286]
Nodo 287 → VD: [1, 7, 41, 287] | VI: [1, 7, 41, 287]
Nodo 288 → VD: [1, 2, 3, 4, 6, 8, 9, 12, 16, 18, 24, 32, 36, 48, 72, 96, 144, 288] | VI: [1, 2, 3, 4, 6, 8, 9, 12, 16, 18, 24, 32, 36, 48, 72, 96, 144, 288]
Nodo 289 → VD: [1, 17, 289] | VI: [1, 17, 289]
Nodo 290 → VD: [1, 2, 5, 10, 29, 58, 145, 290] | VI: [1, 2, 5, 10, 29, 58, 145, 290]
Nodo 291 → VD: [1, 3, 97, 291] | VI: [1, 3, 97, 291]
Nodo 292 → VD: [1, 2, 4, 73, 146, 292] | VI: [1, 2, 4, 73, 146, 292]
Nodo 293 → VD: [1, 293] | VI: [1, 293]
Nodo 294 → VD: [1, 2, 3, 6, 7, 14, 21, 42, 49, 98, 147, 294] | VI: [1, 2, 3, 6, 7, 14, 21, 42, 49, 98, 147, 294]
Nodo 295 → VD: [1, 5, 59, 295] | VI: [1, 5, 59, 295]
Nodo 296 → VD: [1, 2, 4, 8, 37, 74, 148, 296] | VI: [1, 2, 4, 8, 37, 74, 148, 296]
Nodo 297 → VD: [1, 3, 9, 11, 27, 33, 99, 297] | VI: [1, 3, 9, 11, 27, 33, 99, 297]
Nodo 298 → VD: [1, 2, 149, 298] | VI: [1, 2, 149, 298]
Nodo 299 → VD: [1, 13, 23, 299] | VI: [1, 13, 23, 299]
Nodo 300 → VD: [1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 25, 30, 50, 60, 75, 100, 150, 300] | VI: [1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 25, 30, 50, 60, 75, 100, 150, 300]
Nodo 301 → VD: [1, 7, 43, 301] | VI: [1, 7, 43, 301]
Nodo 302 → VD: [1, 2, 151, 302] | VI: [1, 2, 151, 302]
Nodo 303 → VD: [1, 3, 101, 303] | VI: [1, 3, 101, 303]

### Ejercicio 2
Verificar si un grafo dado cumple las propiedades de Reflexividad, Simetría, Antisimetría y Transitividad. Luego, debe decidir si el grafo es un orden o es corresponde a una relación de equivalencia

In [88]:
def cargar_json(path):
    with open(path, 'r') as f:
        data = json.load(f)
    nodos = list(map(int, data["P"]))
    adyacencia = {int(k): list(map(int, v)) for k, v in data["E"].items()}
    return nodos, adyacencia

In [89]:
nodos_1, adyacencias_1 = cargar_json('/content/drive/MyDrive/Estructura de datis/Archivos_2/01.json')
nodos_2, adyacencias_2 = cargar_json('/content/drive/MyDrive/Estructura de datis/Archivos_2/02.json')
nodos_3, adyacencias_3 = cargar_json('/content/drive/MyDrive/Estructura de datis/Archivos_2/03.json')

In [104]:
# Para todo n tiene que existir un par (n,n)
def es_reflexivo(nodos, ady):
    return all(n in ady.get(n, []) for n in nodos)

# Si (a,b) entonces (b, a)
def es_simetrico(ady):
    for a, vecinos in ady.items():
        for b in vecinos:
            if a not in ady.get(b, []):
                return False
    return True

# Si (a,b) y (b,a) enontces no siempre a == b
def es_antisimetrico(ady):
    for a, vecinos in ady.items():
        for b in vecinos:
            if b != a and a in ady.get(b, []):
                return False
    return True


# Si (a,b) y (b,c) entonces (a,c)
def es_transitivo(ady):
    for a, vecinos in ady.items():
        for b in vecinos:
            for c in ady.get(b, []):
                if c not in ady.get(a, []):
                    return False
    return True

# Aca simplemente imprimo y veo si son trues para calcular equivalencia u orden
def analizar_grafo(nodos, ady):
    reflexivo = es_reflexivo(nodos, ady)
    simetrico = es_simetrico(ady)
    antisimetrico = es_antisimetrico(ady)
    transitivo = es_transitivo(ady)

    if reflexivo and simetrico and transitivo:
        print("Es una RELACIÓN DE EQUIVALENCIA")
    elif reflexivo and antisimetrico and transitivo:
        print("Es una RELACIÓN DE ORDEN")
    else:
        print("No es ni una relación de equivalencia ni de orden")

    print(f"Reflexivo: {reflexivo}")
    print(f"Simétrico: {simetrico}")
    print(f"Antisimétrico: {antisimetrico}")
    print(f"Transitivo: {transitivo}")

In [106]:
analizar_grafo(nodos_2, adyacencias_2)

No es ni una relación de equivalencia ni de orden
Reflexivo: True
Simétrico: False
Antisimétrico: False
Transitivo: False

### Ejercicio 3
Implementar el algoritmo de obtención de paso de un nodo a otro de un grafo. La aplicación debe soportar leer el grafo desde un archivo de disco y la salida debe ser una secuencia con los nodos a recorrer para recrear el paso.